name: Deploy
on: [push]
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: bun install
      - name: Build static pages
        run: bun build.ts
      - name: Copy out to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "out/*"
          target: "/var/www/static"
          strip_components: 1
      - name: Copy static to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "static"
          target: "/var/www/static"
          strip-components: 1

